import { Party } from '../types';

export const mockParties: Party[] = [
  {
    id: '1',
    gameTitle: 'Apex Legends',
    hostId: 'u1',
    type: 'rank',
    startAt: '2025-07-25T20:00',
    requireFull: true,
    maxMembers: 3,
    members: [
      {
        id: 'u1',
        name: 'たすく',
        avatarUrl: '/avatar.png',
        device: 'pc',
        isHost: true,
      },
      {
        id: 'u2',
        name: 'にし',
        avatarUrl: '/avatar.png',
        device: 'ps',
      },
    ],
    acceptedDevices: ['pc', 'ps'],
    vcTool: 'Discord',
    rankRange: ['プラチナ', 'ダイヤ'],
    message: 'プラチナ〜ダイヤ帯希望！VCあり',
  },
  {
    id: '2',
    gameTitle: 'Apex Legends',
    hostId: 'u3',
    type: 'casual',
    startAt: '2025-07-25T20:15',
    requireFull: false,
    maxMembers: 3,
    members: [
      {
        id: 'u3',
        name: 'さとう',
        avatarUrl: '/avatar.png',
        device: 'pc',
        isHost: true,
      },
    ],
    acceptedDevices: ['pc'],
    vcTool: 'なし',
    rankRange: [],
    message: 'カジュアル回してます！どなたでもどうぞ',
  },
  {
    id: '3',
    gameTitle: 'Apex Legends',
    hostId: 'u4',
    type: 'rank',
    startAt: '2025-07-25T20:30',
    requireFull: true,
    maxMembers: 3,
    members: [
      {
        id: 'u4',
        name: 'まつもと',
        avatarUrl: '/avatar.png',
        device: 'ps',
        isHost: true,
      },
      {
        id: 'u5',
        name: 'こばやし',
        avatarUrl: '/avatar.png',
        device: 'pc',
      },
    ],
    acceptedDevices: ['ps', 'pc'],
    vcTool: 'Discord',
    rankRange: ['ゴールド', 'プラチナ'],
    message: 'ゴールド〜プラチナ帯。楽しく勝ちたい！',
  },
  {
    id: '4',
    gameTitle: 'Apex Legends',
    hostId: 'u6',
    type: 'casual',
    startAt: '2025-07-25T20:45',
    requireFull: false,
    maxMembers: 3,
    members: [
      {
        id: 'u6',
        name: 'いとう',
        avatarUrl: '/avatar.png',
        device: 'pc',
        isHost: true,
      },
    ],
    acceptedDevices: ['pc', 'ps'],
    vcTool: 'Discord',
    rankRange: [],
    message: '夜中カジュアル遊べる人募集！',
  },
  {
    id: '5',
    gameTitle: 'Apex Legends',
    hostId: 'u7',
    type: 'casual',
    startAt: '2025-07-25T21:00',
    requireFull: true,
    maxMembers: 3,
    members: [
      {
        id: 'u7',
        name: 'たなか',
        avatarUrl: '/avatar.png',
        device: 'ps',
        isHost: true,
      },
    ],
    acceptedDevices: ['ps', 'pc'],
    vcTool: 'なし',
    rankRange: [],
    message: 'カジュアルをのんびり。誰でも歓迎です！',
  },
  {
    id: '6',
    gameTitle: 'Apex Legends',
    hostId: 'u8',
    type: 'rank',
    startAt: '2025-07-25T21:15',
    requireFull: true,
    maxMembers: 3,
    members: [
      {
        id: 'u8',
        name: 'すずき',
        avatarUrl: '/avatar.png',
        device: 'pc',
        isHost: true,
      },
    ],
    acceptedDevices: ['pc', 'ps'],
    vcTool: 'Discord',
    rankRange: ['ダイヤ'],
    message: '深夜ダイヤ帯回せる方募集します！',
  },
  {
    id: '7',
    gameTitle: 'Apex Legends',
    hostId: 'u9',
    type: 'rank',
    startAt: '2025-07-25T21:30',
    requireFull: true,
    maxMembers: 3,
    members: [
      {
        id: 'u9',
        name: 'ささき',
        avatarUrl: '/avatar.png',
        device: 'ps',
        isHost: true,
      },
    ],
    acceptedDevices: ['ps', 'pc'],
    vcTool: 'Discord',
    rankRange: ['ダイヤ', 'マスター'],
    message: 'マスター帯目前！ダイヤ↑の方ぜひ！',
  },
  {
    id: '8',
    gameTitle: 'Apex Legends',
    hostId: 'u10',
    type: 'casual',
    startAt: '2025-07-25T21:45',
    requireFull: false,
    maxMembers: 3,
    members: [
      {
        id: 'u10',
        name: 'やまだ',
        avatarUrl: '/avatar.png',
        device: 'ps',
        isHost: true,
      },
    ],
    acceptedDevices: ['ps', 'pc'],
    vcTool: 'なし',
    rankRange: [],
    message: 'のんびり夜更かし雑談カジュアル🌙',
  },
];