import { Party } from '../types';

export const mockParties: Party[] = [
  {
    id: '1',
    gameTitle: 'Apex Legends',
    hostId: 'u1',
    type: 'rank',
    startAt: '2025-07-25T20:00',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u1', 'u2'],
    acceptedDevices: ['PC', 'PS'],
    vcTool: 'Discord',
    rankRange: ['プラチナ', 'ダイヤ'],
    message: 'プラチナ〜ダイヤ帯希望！VCあり',
  },
  {
    id: '2',
    gameTitle: 'Apex Legends',
    hostId: 'u3',
    type: 'casual',
    startAt: '2025-07-25T20:15',
    requireFull: false,
    maxMembers: 3,
    memberIds: ['u3'],
    acceptedDevices: ['PS'],
    vcTool: 'なし',
    rankRange: [],
    message: 'カジュアル回してます！どなたでもどうぞ',
  },
  {
    id: '3',
    gameTitle: 'Apex Legends',
    hostId: 'u4',
    type: 'rank',
    startAt: '2025-07-25T20:30',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u4', 'u5'],
    acceptedDevices: ['PS', 'PC'],
    vcTool: 'Discord',
    rankRange: ['ゴールド', 'プラチナ'],
    message: 'ゴールド〜プラチナ帯。楽しく勝ちたい！',
  },
  {
    id: '4',
    gameTitle: 'Apex Legends',
    hostId: 'u6',
    type: 'casual',
    startAt: '2025-07-25T20:45',
    requireFull: false,
    maxMembers: 3,
    memberIds: ['u6'],
    acceptedDevices: ['PC', 'PS'],
    vcTool: 'Discord',
    rankRange: [],
    message: '夜中カジュアル遊べる人募集！',
  },
  {
    id: '5',
    gameTitle: 'Apex Legends',
    hostId: 'u7',
    type: 'casual',
    startAt: '2025-07-25T21:00',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u7'],
    acceptedDevices: ['PS', 'PC'],
    vcTool: 'なし',
    rankRange: [],
    message: 'カジュアルをのんびり。誰でも歓迎です！',
  },
  {
    id: '6',
    gameTitle: 'Apex Legends',
    hostId: 'u8',
    type: 'rank',
    startAt: '2025-07-25T21:15',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u8'],
    acceptedDevices: ['PC', 'PS'],
    vcTool: 'Discord',
    rankRange: ['ダイヤ'],
    message: '深夜ダイヤ帯回せる方募集します！',
  },
  {
    id: '7',
    gameTitle: 'Apex Legends',
    hostId: 'u9',
    type: 'rank',
    startAt: '2025-07-25T21:30',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u9'],
    acceptedDevices: ['PS', 'PC'],
    vcTool: 'Discord',
    rankRange: ['ダイヤ', 'マスター'],
    message: 'マスター帯目前！ダイヤ↑の方ぜひ！',
  },
  {
    id: '8',
    gameTitle: 'Apex Legends',
    hostId: 'u10',
    type: 'casual',
    startAt: '2025-07-25T21:45',
    requireFull: false,
    maxMembers: 3,
    memberIds: ['u10'],
    acceptedDevices: ['PS', 'PC'],
    vcTool: 'なし',
    rankRange: [],
    message: 'のんびり夜更かし雑談カジュアル🌙',
  },
  {
    id: '9',
    gameTitle: 'Apex Legends',
    hostId: 'u11',
    type: 'rank',
    startAt: '2025-07-25T22:00',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u11', 'u12'],
    acceptedDevices: ['PS'],
    vcTool: 'Discord',
    rankRange: ['プレデター'],
    message: 'プレデター帯ガチ募集中。PS限定でお願いします！',
  },
];