import { Party } from '../types';

export const mockParties: Party[] = [
  {
    id: '000',
    gameTitle: 'Apex Legends',
    hostId: 'u20',
    type: 'casual',
    startAt: null,
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u20', 'u21', 'u22'],
    acceptedDevices: ['PC', 'Switch', 'Xbox'],
    vcTool: 'Discord',
    rankRange: [],
    message: '満員ですが、キャンセル出たらすぐ入れます！',
    playStyleTag: 'エンジョイ',
    ageTag: '誰でも歓迎',
  },
  {
    id: '00',
    gameTitle: 'Apex Legends',
    hostId: 'u0',
    type: 'rank',
    startAt: null,
    requireFull: false,
    maxMembers: 3,
    memberIds: ['u0'],
    acceptedDevices: ['PC', 'PS'],
    vcTool: 'Discord',
    rankRange: ['プラチナ', 'ダイヤ'],
    message: '今すぐランク行ける方募集！',
    playStyleTag: 'キルムーブ',
    ageTag: '誰でも歓迎',
  },
  {
    id: '0',
    gameTitle: 'Apex Legends',
    hostId: 'u23',
    type: 'casual',
    startAt: null,
    requireFull: false,
    maxMembers: 3,
    memberIds: ['u23'],
    acceptedDevices: ['PC', 'PS'],
    vcTool: 'Discord',
    rankRange: [],
    message: '今すぐプレイできる方募集中！気軽にどうぞ',
    playStyleTag: 'エンジョイ',
    ageTag: '誰でも歓迎',
  },
  {
    id: '1',
    gameTitle: 'Apex Legends',
    hostId: 'u1',
    type: 'rank',
    startAt: '2025-07-25T20:00',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u1', 'u2'],
    acceptedDevices: ['PC', 'PS'],
    vcTool: 'Discord',
    rankRange: ['プラチナ', 'ダイヤ'],
    message: 'プラチナ〜ダイヤ帯希望！VCあり',
    playStyleTag: 'キルムーブ',
    ageTag: '20代歓迎',
  },
  {
    id: '2',
    gameTitle: 'Apex Legends',
    hostId: 'u3',
    type: 'casual',
    startAt: '2025-07-25T20:15',
    requireFull: false,
    maxMembers: 3,
    memberIds: ['u3'],
    acceptedDevices: ['PS'],
    vcTool: 'なし',
    rankRange: [],
    message: 'カジュアル回してます！どなたでもどうぞ',
    playStyleTag: 'エンジョイ',
    ageTag: '誰でも歓迎',
  },
  {
    id: '3',
    gameTitle: 'Apex Legends',
    hostId: 'u4',
    type: 'rank',
    startAt: '2025-07-25T20:30',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u4', 'u5'],
    acceptedDevices: ['PS', 'PC'],
    vcTool: 'Discord',
    rankRange: ['ゴールド', 'プラチナ'],
    message: 'ゴールド〜プラチナ帯。楽しく勝ちたい！',
    playStyleTag: 'アンチムーブ',
    ageTag: '20代歓迎',
  },
  {
    id: '4',
    gameTitle: 'Apex Legends',
    hostId: 'u6',
    type: 'casual',
    startAt: '2025-07-25T20:45',
    requireFull: false,
    maxMembers: 3,
    memberIds: ['u6'],
    acceptedDevices: ['PC', 'PS'],
    vcTool: 'Discord',
    rankRange: [],
    message: '夜中カジュアル遊べる人募集！',
    playStyleTag: 'エンジョイ',
    ageTag: '30代以上歓迎',
  },
  {
    id: '5',
    gameTitle: 'Apex Legends',
    hostId: 'u7',
    type: 'casual',
    startAt: '2025-07-25T21:00',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u7'],
    acceptedDevices: ['PS', 'PC', 'Switch'],
    vcTool: 'なし',
    rankRange: [],
    message: 'カジュアルをのんびり。誰でも歓迎です！',
    playStyleTag: 'エンジョイ',
    ageTag: '誰でも歓迎',
  },
  {
    id: '6',
    gameTitle: 'Apex Legends',
    hostId: 'u8',
    type: 'rank',
    startAt: '2025-07-25T21:15',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u8'],
    acceptedDevices: ['PC', 'PS'],
    vcTool: 'Discord',
    rankRange: ['ダイヤ'],
    message: '深夜ダイヤ帯回せる方募集します！',
    playStyleTag: 'ハイド',
    ageTag: '20代歓迎',
  },
  {
    id: '7',
    gameTitle: 'Apex Legends',
    hostId: 'u9',
    type: 'rank',
    startAt: '2025-07-25T21:30',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u9'],
    acceptedDevices: ['PS', 'PC'],
    vcTool: 'Discord',
    rankRange: ['ダイヤ', 'マスター'],
    message: 'マスター帯目前！ダイヤ↑の方ぜひ！',
    playStyleTag: 'キルムーブ',
    ageTag: '20代歓迎',
  },
  {
    id: '8',
    gameTitle: 'Apex Legends',
    hostId: 'u10',
    type: 'casual',
    startAt: '2025-07-25T21:45',
    requireFull: false,
    maxMembers: 3,
    memberIds: ['u10'],
    acceptedDevices: ['PS', 'PC'],
    vcTool: 'なし',
    rankRange: [],
    message: 'のんびり夜更かし雑談カジュアル🌙',
    playStyleTag: 'エンジョイ',
    ageTag: '30代以上歓迎',
  },
  {
    id: '9',
    gameTitle: 'Apex Legends',
    hostId: 'u11',
    type: 'rank',
    startAt: '2025-07-25T22:00',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u11', 'u12'],
    acceptedDevices: ['PS'],
    vcTool: 'Discord',
    rankRange: ['プレデター'],
    message: 'プレデター帯ガチ募集中。PS限定でお願いします！',
    playStyleTag: 'キルムーブ',
    ageTag: '10代歓迎',
  },
  {
    id: '10',
    gameTitle: 'Apex Legends',
    hostId: 'u13',
    type: 'casual',
    startAt: '2025-07-25T22:15',
    requireFull: false,
    maxMembers: 3,
    memberIds: ['u13'],
    acceptedDevices: ['PC'],
    vcTool: 'Discord',
    rankRange: [],
    message: '気楽にいきましょう～！',
    playStyleTag: 'エンジョイ',
    ageTag: '20代歓迎',
  },
  {
    id: '11',
    gameTitle: 'Apex Legends',
    hostId: 'u14',
    type: 'rank',
    startAt: '2025-07-25T22:30',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u14'],
    acceptedDevices: ['PC', 'PS'],
    vcTool: 'Discord',
    rankRange: ['プラチナ'],
    message: '立ち回り重視、報告しっかりできる方希望',
    playStyleTag: 'アンチムーブ',
    ageTag: '30代以上歓迎',
  },
  {
    id: '12',
    gameTitle: 'Apex Legends',
    hostId: 'u15',
    type: 'casual',
    startAt: '2025-07-25T22:45',
    requireFull: false,
    maxMembers: 3,
    memberIds: ['u15'],
    acceptedDevices: ['Xbox'],
    vcTool: 'なし',
    rankRange: [],
    message: '初心者歓迎！気軽に遊びましょう🎮',
    playStyleTag: 'エンジョイ',
    ageTag: '誰でも歓迎',
  },
  {
    id: '13',
    gameTitle: 'Apex Legends',
    hostId: 'u16',
    type: 'rank',
    startAt: '2025-07-25T23:00',
    requireFull: true,
    maxMembers: 3,
    memberIds: ['u16'],
    acceptedDevices: ['PC', 'Xbox'],
    vcTool: 'Discord',
    rankRange: ['ゴールド', 'プラチナ'],
    message: '立ち回り重視で丁寧に進めたい方歓迎！',
    playStyleTag: 'アンチムーブ',
    ageTag: '30代以上歓迎',
  },
  {
    id: '14',
    gameTitle: 'Apex Legends',
    hostId: 'u17',
    type: 'casual',
    startAt: '2025-07-25T23:15',
    requireFull: false,
    maxMembers: 3,
    memberIds: ['u17'],
    acceptedDevices: ['Switch'],
    vcTool: 'なし',
    rankRange: [],
    message: 'Switch勢でも気軽にどうぞ！🌟',
    playStyleTag: 'ハイド',
    ageTag: '10代歓迎',
  },
];