import { Party } from '../types';

export const mockParties: Party[] = [
  {
    id: '1',
    gameTitle: 'Apex Legends',
    hostId: 'u1',
    type: 'rank',
    startAt: '2025-07-25T20:00',
    requireFull: true,
    maxMembers: 3,
    members: [
      {
        id: 'u1',
        name: 'とよだ',
        avatarUrl: 'https://ui-avatars.com/api/?name=とよだ&background=random',
        device: 'pc',
        isHost: true,
        ingameId: 'game_u1',
        vcId: 'vc_u1',
      },
      {
        id: 'u2',
        name: 'にし',
        avatarUrl: 'https://ui-avatars.com/api/?name=にし&background=random',
        device: 'ps',
        ingameId: 'game_u2',
        vcId: 'vc_u2',
      },
    ],
    acceptedDevices: ['pc', 'ps'],
    vcTool: 'Discord',
    rankRange: ['プラチナ', 'ダイヤ'],
    message: 'プラチナ〜ダイヤ帯希望！VCあり',
  },
  {
    id: '2',
    gameTitle: 'Apex Legends',
    hostId: 'u3',
    type: 'casual',
    startAt: '2025-07-25T20:15',
    requireFull: false,
    maxMembers: 3,
    members: [
      {
        id: 'u3',
        name: 'さとう',
        avatarUrl: 'https://ui-avatars.com/api/?name=さとう&background=random',
        device: 'pc',
        isHost: true,
        ingameId: 'game_u3',
        vcId: 'vc_u3',
      },
    ],
    acceptedDevices: ['pc'],
    vcTool: 'なし',
    rankRange: [],
    message: 'カジュアル回してます！どなたでもどうぞ',
  },
  {
    id: '3',
    gameTitle: 'Apex Legends',
    hostId: 'u4',
    type: 'rank',
    startAt: '2025-07-25T20:30',
    requireFull: true,
    maxMembers: 3,
    members: [
      {
        id: 'u4',
        name: 'まつもと',
        avatarUrl: 'https://ui-avatars.com/api/?name=まつもと&background=random',
        device: 'ps',
        isHost: true,
        ingameId: 'game_u4',
        vcId: 'vc_u4',
      },
      {
        id: 'u5',
        name: 'こばやし',
        avatarUrl: 'https://ui-avatars.com/api/?name=こばやし&background=random',
        device: 'pc',
        ingameId: 'game_u5',
        vcId: 'vc_u5',
      },
    ],
    acceptedDevices: ['ps', 'pc'],
    vcTool: 'Discord',
    rankRange: ['ゴールド', 'プラチナ'],
    message: 'ゴールド〜プラチナ帯。楽しく勝ちたい！',
  },
  {
    id: '4',
    gameTitle: 'Apex Legends',
    hostId: 'u6',
    type: 'casual',
    startAt: '2025-07-25T20:45',
    requireFull: false,
    maxMembers: 3,
    members: [
      {
        id: 'u6',
        name: 'いとう',
        avatarUrl: 'https://ui-avatars.com/api/?name=いとう&background=random',
        device: 'pc',
        isHost: true,
        ingameId: 'game_u6',
        vcId: 'vc_u6',
      },
    ],
    acceptedDevices: ['pc', 'ps'],
    vcTool: 'Discord',
    rankRange: [],
    message: '夜中カジュアル遊べる人募集！',
  },
  {
    id: '5',
    gameTitle: 'Apex Legends',
    hostId: 'u7',
    type: 'casual',
    startAt: '2025-07-25T21:00',
    requireFull: true,
    maxMembers: 3,
    members: [
      {
        id: 'u7',
        name: 'たなか',
        avatarUrl: 'https://ui-avatars.com/api/?name=たなか&background=random',
        device: 'ps',
        isHost: true,
        ingameId: 'game_u7',
        vcId: 'vc_u7',
      },
    ],
    acceptedDevices: ['ps', 'pc'],
    vcTool: 'なし',
    rankRange: [],
    message: 'カジュアルをのんびり。誰でも歓迎です！',
  },
  {
    id: '6',
    gameTitle: 'Apex Legends',
    hostId: 'u8',
    type: 'rank',
    startAt: '2025-07-25T21:15',
    requireFull: true,
    maxMembers: 3,
    members: [
      {
        id: 'u8',
        name: 'すずき',
        avatarUrl: 'https://ui-avatars.com/api/?name=すずき&background=random',
        device: 'pc',
        isHost: true,
        ingameId: 'game_u8',
        vcId: 'vc_u8',
      },
    ],
    acceptedDevices: ['pc', 'ps'],
    vcTool: 'Discord',
    rankRange: ['ダイヤ'],
    message: '深夜ダイヤ帯回せる方募集します！',
  },
  {
    id: '7',
    gameTitle: 'Apex Legends',
    hostId: 'u9',
    type: 'rank',
    startAt: '2025-07-25T21:30',
    requireFull: true,
    maxMembers: 3,
    members: [
      {
        id: 'u9',
        name: 'ささき',
        avatarUrl: 'https://ui-avatars.com/api/?name=ささき&background=random',
        device: 'ps',
        isHost: true,
        ingameId: 'game_u9',
        vcId: 'vc_u9',
      },
    ],
    acceptedDevices: ['ps', 'pc'],
    vcTool: 'Discord',
    rankRange: ['ダイヤ', 'マスター'],
    message: 'マスター帯目前！ダイヤ↑の方ぜひ！',
  },
  {
    id: '8',
    gameTitle: 'Apex Legends',
    hostId: 'u10',
    type: 'casual',
    startAt: '2025-07-25T21:45',
    requireFull: false,
    maxMembers: 3,
    members: [
      {
        id: 'u10',
        name: 'やまだ',
        avatarUrl: 'https://ui-avatars.com/api/?name=やまだ&background=random',
        device: 'ps',
        isHost: true,
        ingameId: 'game_u10',
        vcId: 'vc_u10',
      },
    ],
    acceptedDevices: ['ps', 'pc'],
    vcTool: 'なし',
    rankRange: [],
    message: 'のんびり夜更かし雑談カジュアル🌙',
  },
];